//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Общее_УП
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int Code_book { get; set; }
        public string Title_book { get; set; }
        public Nullable<int> Code_author { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> Code_publish { get; set; }
        public string image { get; set; }

        public string name_author { get { return Authors.name_author; } }
        public string name_publish { get { return Publishing_house.Publish; } }

        public virtual Authors Authors { get; set; }
        public virtual Publishing_house Publishing_house { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
    }
}
