//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Общее_УП
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public int Code_purchase { get; set; }
        public Nullable<int> Code_book { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public Nullable<int> Code_delivery { get; set; }
        public Nullable<bool> Type_purchase { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Amount { get; set; }

        public string Name_book { get { return Books.Title_book; } }
        public string Name_del { get { return Deliveries.Name_company; } }
        public virtual Books Books { get; set; }
        public virtual Deliveries Deliveries { get; set; }
    }
}
